spring:
  profiles:
    active: native
  application:
    name: configserver

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}