server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # 配置路由
      routes:
        - id: partService
          uri: lb://service-provider
          predicates:
            - Path=/*/**
eureka:
  client:
    register-with-eureka: true # 是否将自己注册到eureka注册中心
    fetch-registry: true # 是否从eureka注册中心获取注册信息
    service-url:
      defaultZone: http://localhost:8080/eureka/
