/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80020
 Source Host           : localhost:3306
 Source Schema         : weixin

 Target Server Type    : MySQL
 Target Server Version : 80020
 File Encoding         : 65001

 Date: 01/09/2025 20:38:36
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for ai_config
-- ----------------------------
DROP TABLE IF EXISTS `ai_config`;
CREATE TABLE `ai_config`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录明细ID，主键',
  `ai_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'AI平台名称',
  `ai_token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'AI平台token',
  `ai_model` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'AI平台模型',
  `ai_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'AI平台接口地址',
  `ai_headers_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'AI平台请求头参数',
  `ai_jsonBody_json` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'AI参数请求体参数',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 88 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of ai_config
-- ----------------------------
INSERT INTO `ai_config` VALUES (23, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen3-30B-A3B-Instruct-2507', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (24, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen3-235B-A22B-Thinking-2507', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (25, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen3-235B-A22B-Instruct-2507', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (26, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'baidu/ERNIE-4.5-300B-A47B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (27, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'moonshotai/Kimi-K2-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (28, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'ascend-tribe/pangu-pro-moe', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (29, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'tencent/Hunyuan-A13B-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (30, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'MiniMaxAI/MiniMax-M1-80k', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (31, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Tongyi-Zhiwen/QwenLong-L1-32B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (32, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen3-30B-A3B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (33, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen3-32B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (34, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen3-14B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (35, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen3-8B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (36, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen3-235B-A22B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (37, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'THUDM/GLM-Z1-32B-0414', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (38, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'THUDM/GLM-4-32B-0414', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (39, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'THUDM/GLM-Z1-Rumination-32B-0414', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (40, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'THUDM/GLM-4-9B-0414', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (41, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'THUDM/GLM-4-9B-0414', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (42, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/QwQ-32B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (43, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Pro/deepseek-ai/DeepSeek-R1', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (44, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Pro/deepseek-ai/DeepSeek-V3', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (45, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'deepseek-ai/DeepSeek-R1', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (46, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'deepseek-ai/DeepSeek-V3', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (47, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'deepseek-ai/DeepSeek-R1-0528-Qwen3-8B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (48, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (49, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-14B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (50, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (51, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Pro/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (52, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'deepseek-ai/DeepSeek-V2.5', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (53, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen2.5-72B-Instruct-128K', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (54, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen2.5-72B-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (55, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen2.5-32B-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (56, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen2.5-14B-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (57, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen2.5-7B-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (58, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen2.5-Coder-32B-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (59, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Qwen/Qwen2.5-Coder-7B-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (60, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Pro/Qwen/Qwen2-7B-Instruct', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (61, '硅基流动', 'sk-vcpuhpuqxnvduubjkfquwvgqziowgeekawpdagqzecxyvrzf', 'Pro/THUDM/glm-4-9b-chat', 'https://api.siliconflow.cn/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (62, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4.5', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (63, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4.5-air', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (64, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4.5-x', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (65, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4.5-airx', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (66, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4.5-flash', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (67, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4-plus', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (68, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4-air-250414', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (69, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4-airx', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (70, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4-flashx', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (71, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4-flashx-250414', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (72, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-z1-air', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (73, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-z1-airx', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (74, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-z1-flash', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (75, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-z1-flashx', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (76, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4v-plus-0111', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (77, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4v-flash', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (78, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4.1v-thinking-flashx', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (79, '智谱AI', 'cf5431d9508f4a45be95b648d9634683.1XcQwYAxLGy3gkr6', 'glm-4.1v-thinking-flash', 'https://open.bigmodel.cn/api/paas/v4/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (80, 'openrouter', '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', 'mistralai/mistral-small-3.2-24b-instruct:free', 'https://openrouter.ai/api/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (81, 'openrouter', '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', 'cognitivecomputations/dolphin-mistral-24b-venice-edition:free', 'https://openrouter.ai/api/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (82, 'openrouter', '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', 'tencent/hunyuan-a13b-instruct:free', 'https://openrouter.ai/api/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (83, 'openrouter', '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', 'moonshotai/kimi-dev-72b:free', 'https://openrouter.ai/api/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (84, 'openrouter', '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', 'qwen/qwen3-30b-a3b:free', 'https://openrouter.ai/api/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (85, 'openrouter', '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', 'mistralai/mistral-small-3.1-24b-instruct:free', 'https://openrouter.ai/api/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (86, 'openrouter', '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', 'qwen/qwen2.5-vl-72b-instruct:free', 'https://openrouter.ai/api/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');
INSERT INTO `ai_config` VALUES (87, 'openrouter', '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', 'mistralai/mistral-nemo:free', 'https://openrouter.ai/api/v1/chat/completions', '{\"Content-Type\":\"application/json\",\"Authorization\":\"Bearer \"}', '{\"model\": \"\", \"messages\": [{\"role\": \"user\", \"content\": \"\"}]}');

SET FOREIGN_KEY_CHECKS = 1;
