server:
  port: 8080
spring:
  application:
    name: cloud-register-server
# 配置 eureka 服务端
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 是否将自己注册到eureka注册中心
    fetch-registry: false # 是否从eureka注册中心获取注册信息
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
